version: '3'

services:

  redis:
    image: redis:3.2.9

  web:
    build:
      context: .
    command: bundle exec puma -I . -C config/puma.rb
    environment:
      - FORCE_SSL=false
      - ROUTEMASTER_REDIS_URL=redis://redis:6379/0
      - PORT=3000
      - PUMA_BOOT_TIMEOUT=5
      - PUMA_TIMEOUT=5
      - PUMA_THREADS=1
      - PUMA_WORKERS=1
    links:
      - redis
    ports:
      - "3000:3000"

  worker:
    build:
      context: .
    command: bundle exec bin/worker
    environment:
      - ROUTEMASTER_REDIS_URL=redis://redis:6379/0
