version: '3.6'

services:

  redis:
    image: redis:3.2.9
    networks:
      db:

  web:
    build:
      context: .
    command: bundle exec puma -I . -C config/puma.rb
    environment:
      - FORCE_SSL=false
      - ROUTEMASTER_REDIS_URL=redis://redis:6379/0
      - PORT=3000
      - PUMA_BOOT_TIMEOUT=5
      - PUMA_TIMEOUT=5
      - PUMA_THREADS=1
      - PUMA_WORKERS=1
    depends_on:
      - redis
    networks:
      db:
    ports:
      - 3000

  worker:
    build:
      context: .
    command: bundle exec bin/worker
    environment:
      - ROUTEMASTER_REDIS_URL=redis://redis:6379/0
    networks:
      db:

networks:
  db:
