defaults: &defaults
  working_directory: /routemaster

version: 2

docker_version: &docker_version 17.06.0-ce

jobs:
  build:
    <<: *defaults
    steps:
      - setup_remote_docker:
          version: *docker_version
          reusable: true

      - checkout
      - run: echo BUILT

  test:
    <<: *defaults
    steps:
      - setup_remote_docker:
          version: *docker_version
          reusable: true

      - checkout

      - run: ci down
      - run: ci build
      - run: ci run --rm wait wfi redis:6379
      - run: ci run --rm app bin/test_and_report

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
