defaults: &defaults
  working_directory: /routemaster
  docker:
    - image: deliveroo/circleci:0.1.8

version: 2

jobs:
  run_test_suite:
    <<: *defaults

    steps:
      - setup_remote_docker:
          reusable: true

      - checkout

      - run:
          name: Ensure clean slate
          command: ci down

      - run:
          name: Build composition
          command: ci build

      - run:
          name: Wait for Redis to start
          command: ci run --rm wait wfi redis:6379

      - run:
          name: Run RSpec and report test results
          command: ci run --rm app bin/test_and_report

  build_image:
    <<: *defaults

    steps:
      - setup_remote_docker:
          reusable: true

      - checkout

      - run: echo BUILT

workflows:
  version: 2
  test_and_build:
    jobs:
      - run_test_suite
      - build_image:
          requires:
            - run_ci
