defaults: &defaults
  working_directory: /routemaster
  docker:
    - image: deliveroo/circleci:0.1.0

version: 2

jobs:
  run_ci_1: &test_run
    <<: *defaults

    steps:
      - setup_remote_docker:
          reusable: true

      - checkout

      - run:
          name: Ensure clean slate
          command: ci down

      - run:
          name: Build composition
          command: ci build

      - run:
          name: Wait for Redis to start
          command: ci run --rm wait wfi redis:6379

      - run:
          name: Run RSpec and report test results
          command: ci run --rm app bin/test_and_report

  run_ci_2:
    <<: *test_run

  run_ci_3:
    <<: *test_run

  run_ci_4:
    <<: *test_run

  run_ci_5:
    <<: *test_run

  build_image:
    <<: *defaults

    steps:
      - setup_remote_docker:
          reusable: true

      - checkout

      - run:
          name: Build production image
          command: docker build -f Dockerfile -t routemaster .

workflows:
  version: 2
  test_and_build:
    jobs:
      - run_ci_1
      - run_ci_2
      - run_ci_3
      - run_ci_4
      - run_ci_5
      - build_image
