version: '1'

services:
  worker:
    containerDefinitions:
      worker:
        cpu: 256
        memory: 1024
        linuxParameters:
          initProcessEnabled: true
        command: "foreman start worker"
