version: '1'

container_defaults: &container_defaults
  cpu: 1024
  memory: 1024
  essential: true

web_defaults: &web_defaults
  <<: *container_defaults
  command: "bundle exec dotenv puma -I . -p 8000 -C config/puma.rb"

worker_defaults: &worker_defaults
  <<: *container_defaults
  command: "bundle exec dotenv bin/worker"

services:
  elasticache3-public-web:
    containerDefinitions:
      elasticache3-public-web:
        <<: *web_defaults

  elasticache3-internal:
    containerDefinitions:
      elasticache3-internal:
        <<: *web_defaults

  elasticache3-worker:
    containerDefinitions:
      elasticache3-worker:
        <<: *worker_defaults

  rl-public-web:
    containerDefinitions:
      rl-public-web:
        <<: *web_defaults

  rl-internal:
    containerDefinitions:
      rl-internal:
        <<: *web_defaults

  rl-worker:
    containerDefinitions:
      rl-worker:
        <<: *worker_defaults
