version: '1'

services:
  web:
    containerDefinitions:
      web:
        cpu: 1024
        memory: 1024
        essential: true
        command: "bundle exec dotenv puma -I . -p 8000 -C config/puma.rb"

  public-web:
    containerDefinitions:
      public-web:
        cpu: 1024
        memory: 1024
        essential: true
        command: "bundle exec dotenv puma -I . -p 8000 -C config/puma.rb"

  worker:
    containerDefinitions:
      worker:
        cpu: 1024
        memory: 1024
        essential: true
        command: "bundle exec dotenv bin/worker"
