#!/usr/bin/env ruby

require 'tunnels'

$stdout.sync = true
$stderr.sync = true

Kernel.trap('INT') do
  $stderr.puts 'tunnel terminated'
  exit 0
end

Kernel.trap('TERM') do
  $stderr.puts 'tunnel terminated'
  exit 0
end

Tunnels.run!(*ARGV)
