# Report test coverage
require 'simplecov'
SimpleCov.start

require 'dotenv'
Dotenv.load!('.env.test', '.env')

require 'pry'
require 'pry-remote'
require 'rspec/its'
require 'timeout'

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.run_all_when_everything_filtered = false
  config.raise_errors_for_deprecations!

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'

  # We have some long-running tests that can be prone to flakiness.
  # This timeout forces a stack trace to print, event in the CI server.
  config.around do |example|
    Timeout.timeout(15) do
      example.run
    end
  end
end
